#!/usr/bin/env bash
#
# sync.sh — .claude/ の routing 3木を Cursor が読む .cursor/ 配下へ機械射影する。
#
# なぜ:
#   Cursor 2.4 で subagents / skills が入り、Cursor は次を読むようになった。
#     - subagents: .cursor/agents/ と .claude/agents/（独立コンテキスト・自動/手動/並列）
#     - skills:    .cursor/skills/<name>/SKILL.md のみ（.claude/skills は読まない）
#     - rules:     .cursor/rules/**/*.mdc（globs ゲート＝paths ゲートの同義）
#   よって .claude を SSOT のまま、その純粋な射影として .cursor を吐けば、Cursor でも
#   常駐ゼロで同じ routing が効き、develop の「別コンテキストの独立オラクル分離」も保たれる。
#
# 射影（.claude → .cursor）:
#   rules/**/*.md   → rules/**/*.mdc   frontmatter `paths:`→`globs:`+`alwaysApply:false`
#   skills/*/SKILL.md → skills/*/SKILL.md   複製（frontmatter は互換なので原文のまま）
#   agents/**/*.md  → agents/**/*.md   複製＋`model:`を`inherit`へ正規化（opus は Cursor で不解決の恐れ。実モデルは Task 起動時に orchestrator が選ぶ）
#     ※ `tools:` は Cursor が解釈しないが害は無いので残す。read-only の規律は各 body の指示で担保。
#
# 使い方:
#   sync.sh [CLAUDE_DIR] [CURSOR_DIR]
#     CLAUDE_DIR  省略時: $PWD/.claude
#     CURSOR_DIR  省略時: $PWD/.cursor

set -euo pipefail

CLAUDE_DIR="${1:-$PWD/.claude}"
CURSOR_DIR="${2:-$PWD/.cursor}"

MARK='GENERATED by harness cursor-sync'
MARK_LEGACY='GENERATED by claude-harness cursor-sync'

log()  { echo "[cursor-sync] $*"; }
die()  { echo "[cursor-sync] error: $*" >&2; exit 1; }

[[ -d "${CLAUDE_DIR}" ]] || die "claude dir not found: ${CLAUDE_DIR}"
CLAUDE_DIR="$(cd "${CLAUDE_DIR}" && pwd)"

# 既存の生成物（MARK 付きのみ）を掃除。手書き .mdc / SKILL.md / agent は保護する。
cleanup()
{
  local base="$1"
  [[ -d "${base}" ]] || return 0
  while IFS= read -r -d '' f; do
    if grep -q "${MARK}" "${f}" 2>/dev/null || grep -q "${MARK_LEGACY}" "${f}" 2>/dev/null; then
      rm -f "${f}"
    fi
  done < <(find "${base}" -type f \( -name '*.mdc' -o -name '*.md' \) -print0)
}

# ---- rules: paths → globs（Auto Attached） -------------------------------
project_rules()
{
  local src_root="${CLAUDE_DIR}/rules"
  local out_root="${CURSOR_DIR}/rules"
  [[ -d "${src_root}" ]] || { log "no rules/ — skip"; return 0; }

  local n=0
  while IFS= read -r -d '' src; do
    local rel="${src#"${src_root}"/}"
    local out="${out_root}/${rel%.md}.mdc"
    mkdir -p "$(dirname "${out}")"
    awk -v src_rel="rules/${rel}" -v mark="${MARK}" '
      NR==1 && $0!="---" { stage=2 }
      $0=="---" && stage==0 { stage=1; next }
      stage==1 && $0=="---" { stage=2; next }
      stage==1 {
        if ($0 ~ /^[[:space:]]*-[[:space:]]/) {
          g=$0; sub(/^[[:space:]]*-[[:space:]]*/, "", g)
          gsub(/^["'\''[:space:]]+|["'\''[:space:]]+$/, "", g)
          if (g != "") globs[++gn]=g
        }
        next
      }
      stage==2 {
        body[++m]=$0
        if (desc=="" && $0 ~ /^#[[:space:]]/) { d=$0; sub(/^#+[[:space:]]*/, "", d); desc=d }
      }
      END {
        gl=""; for (i=1;i<=gn;i++) gl = gl (i>1 ? ", " : "") globs[i]
        print "---"
        if (desc != "") print "description: " desc
        print "globs: " gl
        print "alwaysApply: false"
        print "---"
        print "<!-- " mark " from .claude/" src_rel " — do not edit; fix the source and re-run init.sh cursor -->"
        for (i=1;i<=m;i++) print body[i]
      }
    ' "${src}" > "${out}"
    n=$((n+1))
  done < <(find "${src_root}" -type f -name '*.md' -print0)
  log "rules:  ${n} → ${out_root}"
}

# ---- verbatim 複製（skills / agents）: frontmatter を保ちつつ MARK を刻む ----
#   $1 src file, $2 out file, $3 mode(skill|agent), $4 src_rel
emit_verbatim()
{
  local src="$1" out="$2" mode="$3" src_rel="$4"
  mkdir -p "$(dirname "${out}")"
  awk -v mode="${mode}" -v mark="${MARK}" -v src_rel="${src_rel}" '
    NR==1 && $0!="---" { stage=2 }
    $0=="---" && stage==0 { print; stage=1; next }
    stage==1 && $0=="---" {
      print
      print "<!-- " mark " from .claude/" src_rel " — do not edit; fix the source and re-run init.sh cursor -->"
      stage=2; next
    }
    stage==1 {
      if (mode=="agent" && $0 ~ /^model:[[:space:]]/) { print "model: inherit"; next }
      print; next
    }
    { print }
  ' "${src}" > "${out}"
}

# ---- skills: .cursor/skills/<name>/SKILL.md ------------------------------
project_skills()
{
  local src_root="${CLAUDE_DIR}/skills"
  local out_root="${CURSOR_DIR}/skills"
  [[ -d "${src_root}" ]] || { log "no skills/ — skip"; return 0; }

  local n=0
  while IFS= read -r -d '' src; do
    local rel="${src#"${src_root}"/}"
    if [[ "${src}" == *.md ]]; then
      emit_verbatim "${src}" "${out_root}/${rel}" skill "skills/${rel}"
    else
      mkdir -p "$(dirname "${out_root}/${rel}")"; cp "${src}" "${out_root}/${rel}"
    fi
    [[ "${src}" == */SKILL.md ]] && n=$((n+1))
  done < <(find "${src_root}" -type f -print0)
  log "skills: ${n} → ${out_root}"
}

# ---- agents: .cursor/agents/**（model を inherit へ正規化） ---------------
project_agents()
{
  local src_root="${CLAUDE_DIR}/agents"
  local out_root="${CURSOR_DIR}/agents"
  [[ -d "${src_root}" ]] || { log "no agents/ — skip"; return 0; }

  local n=0
  while IFS= read -r -d '' src; do
    local rel="${src#"${src_root}"/}"
    emit_verbatim "${src}" "${out_root}/${rel}" agent "agents/${rel}"
    n=$((n+1))
  done < <(find "${src_root}" -type f -name '*.md' -print0)
  log "agents: ${n} → ${out_root}"
}

cleanup "${CURSOR_DIR}/rules"
cleanup "${CURSOR_DIR}/skills"
cleanup "${CURSOR_DIR}/agents"

project_rules
project_skills
project_agents

log "done: ${CLAUDE_DIR} → ${CURSOR_DIR}"
