#!/usr/bin/env python3
"""明示選択された中立 APM パッケージを legacy 利用者へ展開する。"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
MARK = 'GENERATED by harness neutral-project'
TARGETS = ('claude', 'cursor', 'grok', 'codex')
TIERS = ('top', 'mid', 'light')


def frontmatter(text):
    if not text.startswith('---\n'):
        raise ValueError('frontmatter がありません')
    header, body = text[4:].split('\n---', 1)
    fields = {}
    for line in header.splitlines():
        if ':' not in line or line.startswith((' ', '#')):
            continue
        key, value = line.split(':', 1)
        value = value.strip()
        if value.startswith(('"', '[')):
            try:
                value = json.loads(value)
            except json.JSONDecodeError:
                pass
        fields[key] = value
    return fields, body.lstrip('\n')


def markdown(fields, body, source):
    header = '\n'.join(key + ': ' + json.dumps(value, ensure_ascii=False) for key, value in fields.items())
    return '---\n' + header + '\n---\n<!-- ' + MARK + ' from ' + source + '; edit packages/, never this file. -->\n\n' + body


def links(text, source, dest):
    def rewrite(match):
        label, url = match.groups()
        address, sep, fragment = url.partition('#')
        if not address or '://' in address or address.startswith('/'):
            return match.group(0)
        resolved = (source.parent / address).resolve()
        if not resolved.exists():
            raise ValueError(f'リンク切れ: {source}: {address}')
        return '[' + label + '](' + os.path.relpath(resolved, dest.parent) + (sep + fragment if sep else '') + ')'
    return re.sub(r'\[([^\]\n]+)\]\(([^)\n]+)\)', rewrite, text)


def digest(content):
    return hashlib.sha256(content.encode()).hexdigest()


def generated(path):
    if not path.is_file():
        return False
    try:
        text = path.read_text()
    except (UnicodeDecodeError, OSError):
        return False
    return any(marker in text for marker in (MARK, 'GENERATED by harness ', 'GENERATED by claude-harness '))


def agent_tier(fields, source):
    tier = fields.pop('x-model-tier', None)
    if tier not in TIERS:
        raise ValueError(f'x-model-tier が不正または未指定です: {source}: {tier!r}')
    return tier


def tier_mapping(config, tier, source):
    tiers = config.get('tiers') or {}
    if config.get('default_tier') not in TIERS or set(tiers) != set(TIERS):
        raise ValueError(f'tier 対応表が不正です: {source}')
    return tiers[tier]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('target', choices=TARGETS)
    parser.add_argument('directory', nargs='?', default='.')
    parser.add_argument('--package', action='append', required=True, dest='packages')
    args = parser.parse_args()
    host = Path(args.directory).resolve()
    if not host.is_dir():
        parser.error('対象ディレクトリがありません')
    # APM の lock と所有ファイルを legacy から変更しない。
    if any((host / name).exists() for name in ('apm.yml', 'apm.yaml', 'apm.lock.yaml', 'apm_modules')):
        parser.error('APM と legacy init は同じ消費プロジェクトで併用できません。apm install を使用してください')
    chosen = sorted(set(args.packages))
    sources = []
    for name in chosen:
        if not re.fullmatch(r'[a-z0-9][a-z0-9-]*', name) or not (ROOT / 'packages' / name / 'apm.yml').is_file():
            parser.error('不明なパッケージ: ' + name)
        sources.append(ROOT / 'packages' / name)
    manifest_path = host / '.harness-legacy.json'
    if manifest_path.is_symlink():
        parser.error('所有 manifest の symlink を辿りません')
    state = json.loads(manifest_path.read_text()) if manifest_path.exists() else {'version': 1, 'targets': {}}
    if state.get('source') not in (None, str(ROOT)):
        parser.error('別 checkout の legacy 生成物です。元 checkout から更新してください')
    # 複数 target の選択が食い違うと手渡し対象が曖昧になるため禁止する。
    for target, record in state['targets'].items():
        if target != args.target and record['packages'] != chosen:
            parser.error('全 target の package 選択を揃えてください。単一 target の選択変更は別の出力先で検証できます')
    output = {}
    pins = json.loads((ROOT / 'tools/codex-sync/models.json').read_text())
    policy = json.loads((ROOT / 'tools/apm/claude-models.json').read_text())
    names = set()
    for package in sources:
        primitives = package / '.apm'
        for source in sorted((primitives / 'skills').rglob('*')) if (primitives / 'skills').exists() else []:
            if not source.is_file():
                continue
            rel = source.relative_to(primitives / 'skills')
            skill_dir = '.agents/skills' if args.target == 'codex' else '.cursor/skills' if args.target == 'cursor' else '.claude/skills'
            dest = host / skill_dir / rel
            if source.suffix == '.md':
                fields, body = frontmatter(source.read_text()) if source.name == 'SKILL.md' else ({}, source.read_text())
                output[dest] = markdown(fields, links(body, source, dest), str(source.relative_to(ROOT)))
                if source.name == 'SKILL.md' and str(fields.get('disable-model-invocation')).lower() == 'true' and args.target == 'codex':
                    output[dest.parent / 'agents/openai.yaml'] = '# ' + MARK + '\nallow_implicit_invocation: false\n'
            else:
                output[dest] = source.read_text()
        for source in sorted((primitives / 'agents').rglob('*.agent.md')) if (primitives / 'agents').exists() else []:
            fields, body = frontmatter(source.read_text())
            name = fields['name']
            tier = agent_tier(fields, source)
            if name in names or not re.fullmatch(r'[a-z0-9][a-z0-9-]*', name):
                raise ValueError('agent 名が重複または不正: ' + name)
            names.add(name)
            directory = '.codex/agents' if args.target == 'codex' else '.' + args.target + '/agents'
            dest = host / directory / (name + ('.toml' if args.target == 'codex' else '.md'))
            body = links(body, source, dest)
            if args.target == 'codex':
                pin = tier_mapping(pins, tier, ROOT / 'tools/codex-sync/models.json')
                result = {'name': name, 'description': fields['description'], 'model': pin['model'], 'model_reasoning_effort': pin['reasoning_effort'], 'developer_instructions': body}
                output[dest] = '# ' + MARK + ' from ' + str(source.relative_to(ROOT)) + '\n' + '\n'.join(k + ' = ' + json.dumps(v, ensure_ascii=False) for k, v in result.items()) + '\n'
            else:
                if args.target == 'claude':
                    fields['model'] = tier_mapping(policy, tier, ROOT / 'tools/apm/claude-models.json')
                elif args.target == 'cursor':
                    fields['model'] = 'inherit'
                output[dest] = markdown(fields, body, str(source.relative_to(ROOT)))
        if args.target in ('claude', 'cursor'):
            for source in sorted((primitives / 'instructions').glob('*.instructions.md')):
                fields, body = frontmatter(source.read_text())
                globs = fields['applyTo'].split(',')
                dest = host / ('.' + args.target) / 'rules' / package.name / (source.name.removesuffix('.instructions.md') + ('.mdc' if args.target == 'cursor' else '.md'))
                metadata = {'paths': globs} if args.target == 'claude' else {'description': fields['description'], 'globs': fields['applyTo'], 'alwaysApply': False}
                output[dest] = markdown(metadata, links(body, source, dest), str(source.relative_to(ROOT)))
    old_files = state['targets'].get(args.target, {}).get('files', {})
    native_roots = ['.agents/skills', '.codex/agents'] if args.target == 'codex' else ['.claude/skills', '.grok/agents'] if args.target == 'grok' else ['.' + args.target + '/' + kind for kind in ('skills', 'agents', 'rules')]
    # Claude/Grok の共有 skill は、初回 target でも他 target の所有 hash を検査する。
    old_files = dict(old_files)
    for record in state['targets'].values():
        for name, expected in record.get('files', {}).items():
            if any(Path(name).is_relative_to(Path(base)) for base in native_roots):
                old_files.setdefault(name, expected)
    cleanup = set()
    for name, expected in old_files.items():
        relative = Path(name)
        if relative.is_absolute() or '..' in relative.parts or not any(relative.is_relative_to(Path(base)) for base in native_roots):
            raise ValueError('所有 manifest のパスが出力境界外です: ' + name)
        candidate = host / relative
        if candidate.is_symlink() or any(parent.is_symlink() for parent in candidate.parents if parent != host):
            raise ValueError('所有 manifest の symlink を辿りません: ' + name)
        shared_hashes = {record.get('files', {}).get(name) for record in state['targets'].values()}
        if candidate.exists() and (not candidate.is_file() or digest(candidate.read_text()) not in shared_hashes):
            raise ValueError('生成後に変更されたファイルを保護します: ' + name)
        cleanup.add(candidate)
    # 過去バージョンのマーカー付き出力も引き継ぐ。無印ファイルは保護する。
    for directory in native_roots:
        base = host / directory
        if base.is_symlink() or any(parent.is_symlink() for parent in base.parents if parent != host):
            raise ValueError('旧 symlink を自動置換しません: ' + str(base))
        if base.exists():
            for candidate in base.rglob('*'):
                if candidate.is_symlink():
                    raise ValueError('生成対象内の symlink を辿りません: ' + str(candidate))
                if generated(candidate):
                    cleanup.add(candidate)
    for dest in output:
        if dest.exists() and dest not in cleanup:
            raise ValueError('手書きファイルを上書きしません: ' + str(dest))
        if any(parent.is_symlink() for parent in dest.parents if parent != host):
            raise ValueError('symlink 配下には出力しません: ' + str(dest))
    for dest in sorted(cleanup - output.keys()):
        if dest.is_file():
            if not generated(dest) and str(dest.relative_to(host)) not in old_files:
                continue
            dest.unlink()
    for dest, content in output.items():
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.exists() or dest.read_text() != content:
            dest.write_text(content)
    for record in state['targets'].values():
        for path, content in output.items():
            relative = str(path.relative_to(host))
            if relative in record.get('files', {}):
                record['files'][relative] = digest(content)
    state['source'] = str(ROOT)
    state['targets'][args.target] = {'packages': chosen, 'files': {str(p.relative_to(host)): digest(s) for p, s in sorted(output.items())}}
    manifest_path.write_text(json.dumps(state, indent=2, ensure_ascii=False) + '\n')
    print(f'{args.target}: {len(output)} files; packages={",".join(chosen)}')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, KeyError, OSError) as error:
        sys.exit('neutral-project: ' + str(error))
