#!/usr/bin/env bash
#
# sync.sh — .claude/agents を Grok Build が読む .grok/agents へ機械射影する。
#
# なぜ:
#   Grok Build は Claude Code 互換で .claude/skills/<name>/SKILL.md をそのまま読む。
#   一方 subagent 定義は .claude/agents/*.md（直下）と .grok/agents/*.md しか見ない。
#   本 harness の agent は手続きキーで一段ネストする（agents/develop/foo.md）ため、
#   ネストを保ったままではカタログに乗らない。
#   rules は Grok が全文ロードするため射影しない（常駐ゼロを壊す）。
#   よって .claude を SSOT のまま、agent だけ name: で flatten して .grok/agents/ へ吐く。
#
# 射影（.claude → .grok）:
#   agents/**/*.md  → agents/<frontmatter name>.md
#     - 出力ファイル名は frontmatter の name:（一意。衝突したら失敗）
#     - model: 行は削除（opus は Grok で不解決。spawn API に per-launch model が無いので親を継承）
#     - tools: は残す（Grok は Claude のツール名を解釈しないが、body の read-only 規律が正）
#   skills / rules は写さない
#
# 使い方:
#   sync.sh [CLAUDE_DIR] [GROK_DIR]
#     CLAUDE_DIR  省略時: $PWD/.claude
#     GROK_DIR    省略時: $PWD/.grok

set -euo pipefail

CLAUDE_DIR="${1:-$PWD/.claude}"
GROK_DIR="${2:-$PWD/.grok}"

MARK='GENERATED by harness grok-sync'
MARK_LEGACY='GENERATED by claude-harness grok-sync'

log()  { echo "[grok-sync] $*"; }
die()  { echo "[grok-sync] error: $*" >&2; exit 1; }

[[ -d "${CLAUDE_DIR}" ]] || die "claude dir not found: ${CLAUDE_DIR}"
CLAUDE_DIR="$(cd "${CLAUDE_DIR}" && pwd)"

extract_name()
{
  awk '
    NR==1 && $0 != "---" { exit }
    $0 == "---" && stage == 0 { stage = 1; next }
    stage == 1 && $0 == "---" { exit }
    stage == 1 && $0 ~ /^name:[[:space:]]/ {
      n = $0
      sub(/^name:[[:space:]]*/, "", n)
      gsub(/^["'\'' ]+|["'\'' ]+$/, "", n)
      print n
      exit
    }
  ' "$1"
}

# 既存の生成物（MARK 付きのみ）を掃除。手書き .grok/agents/*.md は保護する。
cleanup_generated()
{
  local base="$1"
  [[ -d "${base}" ]] || return 0
  while IFS= read -r -d '' f; do
    if grep -q "${MARK}" "${f}" 2>/dev/null || grep -q "${MARK_LEGACY}" "${f}" 2>/dev/null; then
      rm -f "${f}"
    fi
  done < <(find "${base}" -maxdepth 1 -type f -name '*.md' -print0 2>/dev/null)
}

emit_agent()
{
  local src="$1" out="$2" src_rel="$3"
  mkdir -p "$(dirname "${out}")"
  awk -v mark="${MARK}" -v src_rel="${src_rel}" '
    NR==1 && $0 != "---" { stage = 2 }
    $0 == "---" && stage == 0 { print; stage = 1; next }
    stage == 1 && $0 == "---" {
      print
      print "<!-- " mark " from .claude/" src_rel " — do not edit; fix the source and re-run init.sh grok -->"
      stage = 2
      next
    }
    stage == 1 {
      if ($0 ~ /^model:[[:space:]]/) next
      print
      next
    }
    { print }
  ' "${src}" > "${out}"
}

src_root="${CLAUDE_DIR}/agents"
out_root="${GROK_DIR}/agents"

if [[ ! -d "${src_root}" ]]; then
  log "no agents/ — skip"
  exit 0
fi

cleanup_generated "${out_root}"
mkdir -p "${out_root}"

seen=""
n=0

while IFS= read -r -d '' src; do
  local_rel="${src#"${src_root}"/}"
  name="$(extract_name "${src}")"
  [[ -n "${name}" ]] || die "missing frontmatter name: in ${local_rel}"
  [[ "${name}" =~ ^[a-z0-9][a-z0-9-]*$ ]] \
    || die "invalid name: '${name}' in ${local_rel} (lowercase, digits, hyphens)"
  prev="$(printf '%s' "${seen}" | awk -F'\t' -v n="${name}" '$1 == n { print $2; exit }')"
  if [[ -n "${prev}" ]]; then
    die "duplicate name: '${name}' (${prev} and ${local_rel})"
  fi
  seen="${seen}${name}"$'\t'"${local_rel}"$'\n'

  out="${out_root}/${name}.md"
  if [[ -f "${out}" ]] && ! grep -q "${MARK}" "${out}" 2>/dev/null && ! grep -q "${MARK_LEGACY}" "${out}" 2>/dev/null; then
    die "refusing to overwrite hand-written agent: ${out}"
  fi
  emit_agent "${src}" "${out}" "agents/${local_rel}"
  n=$((n + 1))
done < <(find "${src_root}" -type f -name '*.md' -print0)

log "agents: ${n} → ${out_root} (flattened by name:)"
log "done: ${CLAUDE_DIR} → ${GROK_DIR}"
log "note: skills は .claude/skills を直接読む。rules は射影しない（Grok は全文ロードするため）。"
