#!/usr/bin/env bash
#
# sync.sh — .claude/ の skills と agents を Codex が読む場所へ機械射影する。
#
# なぜ:
#   Codex は Claude Code の .claude/skills と .claude/agents を直接は読まない。
#     - skills:  リポジトリの .agents/skills/<name>/SKILL.md
#     - agents:  .codex/agents/*.toml（直下。name / description / developer_instructions）
#     - rules:   paths ゲート相当が無い。全文を AGENTS.md に写すと常駐ゼロを壊すので写さない。
#   よって .claude を SSOT のまま、skills は複製、agents は name: で flatten して TOML にする。
#
# 射影（.claude → Codex）:
#   skills/*/SKILL.md  → .agents/skills/*/SKILL.md
#     - 本文の .claude/ パスはそのまま（tools / rules / templates / agent markdown の SSOT）
#     - disable-model-invocation: true なら agents/openai.yaml に allow_implicit_invocation: false
#   agents/**/*.md     → .codex/agents/<frontmatter name>.toml
#     - 出力ファイル名は frontmatter の name:（一意。衝突したら失敗）
#     - model / model_reasoning_effort は agent の model:（opus/sonnet/haiku＝段）を
#       tools/codex-sync/models.json の tiers で引いた値（ADR-0022 / ADR-0024 / ADR-0025）
#     - tools: は落とす（read-only 規律は body）
#   rules は写さない
#
# 使い方:
#   sync.sh [CLAUDE_DIR] [REPO_DIR]
#     CLAUDE_DIR  省略時: $PWD/.claude
#     REPO_DIR    省略時: $PWD  （.agents/ と .codex/ をここに作る）

set -euo pipefail

CLAUDE_DIR="${1:-$PWD/.claude}"
REPO_DIR="${2:-$PWD}"

MARK='GENERATED by claude-harness codex-sync'

log()  { echo "[codex-sync] $*"; }
die()  { echo "[codex-sync] error: $*" >&2; exit 1; }

[[ -d "${CLAUDE_DIR}" ]] || die "claude dir not found: ${CLAUDE_DIR}"
CLAUDE_DIR="$(cd "${CLAUDE_DIR}" && pwd)"
REPO_DIR="$(cd "${REPO_DIR}" && pwd)"
MODELS_JSON="${CLAUDE_DIR}/tools/codex-sync/models.json"

command -v python3 >/dev/null 2>&1 || die "python3 is required to emit Codex agent TOML"
[[ -f "${MODELS_JSON}" ]] || die "missing Codex model pins: ${MODELS_JSON}"

# 既存の生成物（MARK 付きのみ）を掃除。手書きは保護する。
cleanup_generated()
{
  local base="$1"
  shift
  [[ -d "${base}" ]] || return 0
  while IFS= read -r -d '' f; do
    if grep -q "${MARK}" "${f}" 2>/dev/null; then
      rm -f "${f}"
    fi
  done < <(find "${base}" -type f \( "$@" \) -print0 2>/dev/null)
}

# ---- skills: .agents/skills/<name>/SKILL.md ------------------------------
#   $1 src file, $2 out file, $3 src_rel
emit_skill()
{
  local src="$1" out="$2" src_rel="$3"
  mkdir -p "$(dirname "${out}")"
  awk -v mark="${MARK}" -v src_rel="${src_rel}" '
    NR==1 && $0!="---" { stage=2 }
    $0=="---" && stage==0 { print; stage=1; next }
    stage==1 && $0=="---" {
      print
      print "<!-- " mark " from .claude/" src_rel " — do not edit; fix the source and re-run init.sh codex -->"
      stage=2; next
    }
    stage==1 { print; next }
    { print }
  ' "${src}" > "${out}"
}

project_skills()
{
  local src_root="${CLAUDE_DIR}/skills"
  local out_root="${REPO_DIR}/.agents/skills"
  [[ -d "${src_root}" ]] || { log "no skills/ — skip"; return 0; }

  local n=0
  while IFS= read -r -d '' src; do
    local rel="${src#"${src_root}"/}"
    local out="${out_root}/${rel}"
    if [[ "${src}" == *.md ]]; then
      emit_skill "${src}" "${out}" "skills/${rel}"
    else
      mkdir -p "$(dirname "${out}")"
      cp "${src}" "${out}"
    fi
    if [[ "${src}" == */SKILL.md ]]; then
      n=$((n+1))
      if grep -q '^disable-model-invocation:[[:space:]]*true' "${src}"; then
        local yaml_dir="${out_root}/$(dirname "${rel}")/agents"
        mkdir -p "${yaml_dir}"
        cat > "${yaml_dir}/openai.yaml" <<EOF
# ${MARK} from .claude/skills/${rel} — do not edit; fix the source and re-run init.sh codex
allow_implicit_invocation: false
EOF
      fi
    fi
  done < <(find "${src_root}" -type f -print0)
  log "skills: ${n} → ${out_root}"
}

# ---- agents: .codex/agents/<name>.toml -----------------------------------
extract_name()
{
  awk '
    NR==1 && $0 != "---" { exit }
    $0 == "---" && stage == 0 { stage = 1; next }
    stage == 1 && $0 == "---" { exit }
    stage == 1 && $0 ~ /^name:[[:space:]]/ {
      n = $0
      sub(/^name:[[:space:]]*/, "", n)
      gsub(/^["'\'' ]+|["'\'' ]+$/, "", n)
      print n
      exit
    }
  ' "$1"
}

emit_agent_toml()
{
  local src="$1" out="$2" src_rel="$3" agent_name="$4"
  mkdir -p "$(dirname "${out}")"
  MARK="${MARK}" AGENT_NAME="${agent_name}" CODEX_MODELS_JSON="${MODELS_JSON}" python3 - "${src}" "${out}" "${src_rel}" <<'PY'
import json
import os
import sys
from pathlib import Path

src, out, src_rel = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
mark = os.environ["MARK"]
agent_name = os.environ["AGENT_NAME"]
pins = json.loads(Path(os.environ["CODEX_MODELS_JSON"]).read_text(encoding="utf-8"))
# 段（tier）の SSOT は agent frontmatter の model:。models.json は段→カタログの対応表だけを持つ（ADR-0024 / ADR-0025）。
FAMILY_TIER = {"opus": "top", "sonnet": "mid", "haiku": "light"}
text = src.read_text(encoding="utf-8")
if text.startswith("\ufeff"):
    text = text[1:]
lines = text.splitlines()
if not lines or lines[0].strip() != "---":
    sys.exit(f"missing frontmatter: {src}")

fm = []
i = 1
while i < len(lines):
    if lines[i].strip() == "---":
        body = "\n".join(lines[i + 1 :]).strip("\n")
        break
    fm.append(lines[i])
    i += 1
else:
    sys.exit(f"unclosed frontmatter: {src}")

fields = {}
for line in fm:
    if not line or line.lstrip().startswith("#"):
        continue
    if ":" not in line:
        continue
    key, _, val = line.partition(":")
    key = key.strip()
    val = val.strip().strip("\"'")
    fields[key] = val

name = fields.get("name") or ""
desc = fields.get("description") or ""
if not name:
    sys.exit(f"missing frontmatter name: {src}")
if not desc:
    sys.exit(f"missing frontmatter description: {src}")

tiers = pins.get("tiers") or {}
default_tier = pins.get("default_tier") or "top"
if not tiers:
    sys.exit("missing 'tiers' in models.json (old latest_/lite_ shape? see ADR-0025)")
tier = FAMILY_TIER.get(fields.get("model", "").strip(), default_tier)
pin = tiers.get(tier)
if not pin:
    sys.exit(f"tier '{tier}' (agent {agent_name}) is not in models.json tiers")
model = pin.get("model")
effort = pin.get("reasoning_effort")
for key, val in (("model", model), ("reasoning_effort", effort)):
    if not val:
        sys.exit(f"empty Codex pin {key} for tier '{tier}' in models.json")


def toml_basic(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def toml_multiline(s: str) -> str:
    s = s.replace("\r\n", "\n").replace("\r", "\n")
    s = s.replace("\\", "\\\\").replace('"""', '\\"""')
    return '"""\n' + s.strip("\n") + "\n\"\"\""


out.write_text(
    "\n".join(
        [
            f"# {mark} from .claude/{src_rel} — do not edit; fix the source and re-run init.sh codex",
            f"name = {toml_basic(name)}",
            f"description = {toml_multiline(desc)}",
            f"model = {toml_basic(model)}",
            f"model_reasoning_effort = {toml_basic(effort)}",
            f"developer_instructions = {toml_multiline(body)}",
            "",
        ]
    ),
    encoding="utf-8",
)
PY
}

project_agents()
{
  local src_root="${CLAUDE_DIR}/agents"
  local out_root="${REPO_DIR}/.codex/agents"
  [[ -d "${src_root}" ]] || { log "no agents/ — skip"; return 0; }

  mkdir -p "${out_root}"
  local seen="" n=0

  while IFS= read -r -d '' src; do
    local local_rel="${src#"${src_root}"/}"
    local name
    name="$(extract_name "${src}")"
    [[ -n "${name}" ]] || die "missing frontmatter name: in ${local_rel}"
    [[ "${name}" =~ ^[a-z0-9][a-z0-9-]*$ ]] \
      || die "invalid name: '${name}' in ${local_rel} (lowercase, digits, hyphens)"
    local prev
    prev="$(printf '%s' "${seen}" | awk -F'\t' -v n="${name}" '$1 == n { print $2; exit }')"
    if [[ -n "${prev}" ]]; then
      die "duplicate name: '${name}' (${prev} and ${local_rel})"
    fi
    seen="${seen}${name}"$'\t'"${local_rel}"$'\n'

    local dest="${out_root}/${name}.toml"
    if [[ -f "${dest}" ]] && ! grep -q "${MARK}" "${dest}" 2>/dev/null; then
      die "refusing to overwrite hand-written agent: ${dest}"
    fi
    emit_agent_toml "${src}" "${dest}" "agents/${local_rel}" "${name}"
    n=$((n + 1))
  done < <(find "${src_root}" -type f -name '*.md' -print0)

  log "agents: ${n} → ${out_root} (flattened by name: → .toml; model pins from models.json)"
}

cleanup_generated "${REPO_DIR}/.agents/skills" -name '*.md' -o -name 'openai.yaml'
cleanup_generated "${REPO_DIR}/.codex/agents" -name '*.toml'

project_skills
project_agents

log "done: ${CLAUDE_DIR} → ${REPO_DIR}/.agents/skills + ${REPO_DIR}/.codex/agents"
log "note: rules は射影しない（Codex に paths ゲートが無く、写すと常駐ゼロを壊す）。"
log "      tools / templates は .claude/ を直接 Read する。"
